### ISSUE TITLE
Missing "Images" folder in the template

### ISSUE THREAD

**Issue by nandan75** [Sydney-Informatics-Hub/template-nf#2]
Any reason why the images folder is not part of the template?

I can see that you have used the image link as "user-images.githubusercontent.com" link. 

I can do the above if we are planning to do it as standard practice. Since this is GitHub related, is there a way I can create such links when editing in VS-Code?

For now I have made a folder in Somatic-shortV-nf and I am uploading/linking my workflow image using direct url.

**Comment by georgiesamaha** [comment]
People can add this as needed, doesn't need to be included in the template.
